config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'users' => 'validation#index'
  get 'users/:user_id/validate' => 'validation#validate', as: :validate_user

  resources :questions

  resources :notations do
    resources :questions
  end

  resources :exams do
    resources :notations
    get 'validate' => 'exams#validate', as: :validate
   end

  root 'exams#index'

end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :notation
  has_one :exam, through: :notation

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :user_validated

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.notation = Notation.find(params[:notation_id])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question.notation, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question.notation, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    notation = @question.notation
    @question.destroy
    respond_to do |format|
      format.html { redirect_to notation, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:mark, :comment, :number, :points)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for @question, :html => { :class => 'form-inline' } do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <% if params[:notation_id].blank? %>
    <%= hidden_field_tag(:notation_id, params[:id]) %>
  <% else %>  
    <%= hidden_field_tag(:notation_id, params[:notation_id]) %>
  <% end %>

  <div class="row">
    <%= f.label :number %>
    <%= f.number_field :number, :class => 'form-control small-field' %>
  </div>

  <div class="row">
    <%= f.label :mark, 'Mark & points'%>
    <%= f.text_field :mark, :class => 'form-control small-field' %> on
    <%= f.text_field :points, :class => 'form-control small-field' %>
  </div>

  <div class="row">
    <%= f.label :comment %>
    <%= f.text_area :comment, :class => 'form-control large-field' %>
  </div>
  <div class="actions">
    <%= f.submit 'Save', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/questions/_table.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>Number</th>
    <th>Mark</th>
    <th>Comment</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @questions.each do |question| %>
      <tr>
        <td><%= question.number %></td>
        <td><%= "%g" % question.mark %> / <%= "%g" % question.points %></td>
        <td><%= question.comment %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/questions/edit.html.erb
<h1>Edit a question</h1>

<%= render 'form' %>

<div class="row">
  <%= link_to 'Show', @question %> |
  <%= link_to 'Notation', @question.notation %> |
  <%= link_to 'Exam', @question.exam %> |
  <%= link_to 'Back', :back %>
</div>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<% if @questions.any? %>
    <%= render 'table' %>
<% end %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<div class="row">
  <%= link_to 'Back', :back %>
</div>

app/views/questions/show.html.erb
<p>
  <strong>Mark:</strong>
  <%= "%g" % @question.mark %> on <%= "%g" % @question.points %>
</p>

<p>
  <strong>Appreciation:</strong>
  <%= @question.comment %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Notation', @question.notation %> |
<%= link_to 'Exam', @question.exam %> |
<%= link_to 'Back', :back %>