config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'users' => 'validation#index'
  get 'users/:user_id/validate' => 'validation#validate', as: :validate_user

  resources :questions

  resources :notations do
    resources :questions
  end

  resources :exams do
    resources :notations
    get 'validate' => 'exams#validate', as: :validate
   end

  root 'exams#index'

end

app/models/notation.rb
class Notation < ActiveRecord::Base

  belongs_to :exam
  belongs_to :user
  has_many :questions

  default_scope {
    order('created_at DESC')
  }

end

app/controllers/notations_controller.rb
class NotationsController < ApplicationController
  before_action :set_notation, only: [:show, :edit, :update, :destroy]
  after_action :set_exam_stats, only: [:create, :update, :destroy]
  before_action :user_validated

  # GET /notations
  # GET /notations.json
  def index
    @notations = Notation.all
  end

  # GET /notations/1
  # GET /notations/1.json
  def show
    @questions = @notation.questions
    @question = Question.new
  end

  # GET /notations/new
  def new
    @notation = Notation.new
  end

  # GET /notations/1/edit
  def edit
  end

  # POST /notations
  # POST /notations.json
  def create
    @notation = Notation.new(notation_params)
    @notation.exam_id = params[:exam_id]
    @notation.user = current_user

    respond_to do |format|
      if @notation.save
        format.html { redirect_to @notation, notice: 'Notation was successfully created.' }
        format.json { render :show, status: :created, location: @notation }
      else
        format.html { render :new }
        format.json { render json: @notation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notations/1
  # PATCH/PUT /notations/1.json
  def update
    respond_to do |format|
      if @notation.update(notation_params)
        format.html { redirect_to @notation.exam, notice: 'Notation was successfully updated.' }
        format.json { render :show, status: :ok, location: @notation }
      else
        format.html { render :edit }
        format.json { render json: @notation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notations/1
  # DELETE /notations/1.json
  def destroy
    @exam = @notation.exam

    if @notation.questions.any?
      @notation.questions.each do |q|
        Question.destroy(q)
      end
    end

    @notation.destroy
    respond_to do |format|
      format.html { redirect_to @exam, notice: 'Notation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notation
      @notation = Notation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notation_params
      params.require(:notation).permit(:student, :mark, :results, :appreciation)
    end

    # Used to recalculate average, min & max marks
    def set_exam_stats
      # Set exam for both destroy and other methods
      if @notation.present?
        exam = @notation.exam
      else
        exam = @exam
      end

      exam.average = exam.notations.average(:mark)
      exam.max =  exam.notations.maximum(:mark)
      exam.min =  exam.notations.minimum(:mark)

      if !exam.save
        respond_to do |format|
          format.html { render :edit }
          format.json { render json: @notation.errors, status: :unprocessable_entity }
          end
      end
    end
end

app/helpers/notations_helper.rb
module NotationsHelper
end

app/views/notations/_form.html.erb
<%= form_for @notation, :html => { :class => 'form-inline' } do |f| %>
  <% if @notation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notation.errors.count, "error") %> prohibited this notation from being saved:</h2>

      <ul>
      <% @notation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag(:exam_id, params[:exam_id]) %>

  <div class="row">
    <%= f.label :student %><br>
    <%= f.number_field :student, :class => 'form-control' %>
  </div>
  <div class="row">
    <%= f.label :mark %><br>
    <%= f.text_field :mark, :class => 'form-control small-field' %>
  </div>

  <div class="row">
    <%= f.label :appreciation %><br>
    <%= f.text_area :appreciation, :class => 'form-control large-field' %>
  </div>
  <div class="actions">
    <%= f.submit 'Save', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/notations/_table.erb
<div class="row pull-left form-inline">
  <label for="filter">Filter notations </label>
  <input type="number" class="form-control" id="filter" placeholder="Filter by ID Booster"/>
</div>

<table id="notations-table" class="table table-striped">
  <thead>
  <tr>
    <th>Student</th>
    <th>Mark</th>
    <th>Appreciation</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @notations.each do |notation| %>
      <tr>
        <td class="idbooster"><%= notation.student %></td>
        <td><%= "%g" % notation.mark %></td>
        <td><%= notation.appreciation %></td>
        <td><%= link_to 'Show', notation %></td>
        <td><%= link_to 'Edit', edit_notation_path(notation) %></td>
        <td><%= link_to 'Delete', notation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/notations/edit.html.erb
<h1>Editing notation</h1>

<%= render 'form' %>

<div class="row">
  <%= link_to 'Show', @notation %> |
  <%= link_to 'Exam', @notation.exam %> |
  <%= link_to 'Back', :back %>
</div>

app/views/notations/index.html.erb
<h1>Listing notations</h1>

<div class="row">
    <%= link_to 'New Notation', new_notation_path, :class => 'btn btn-primary' %>
</div>

<% if @notations.any? %>
    <%= render 'table' %>
<% end %>

<br>

app/views/notations/new.html.erb
<h1>New notation</h1>

<%= render 'form' %>

<div class="row">
  <%= link_to 'Back', :back %>
</div>

app/views/notations/show.html.erb
<h2>
  <strong><%= @notation.student %></strong>
</h2>

<p>

  <% if @notation.mark.present? && @notation.mark >= 10 %>
    <strong class="label label-info">
  <% else %>
    <strong class="label label-danger">
  <% end %>
        <%= @notation.mark.blank? ? 'No mark' : "%g" % @notation.mark.to_s() + ' / 20' %></strong>
    </strong>

</p>

<p>
  <%= @notation.appreciation.blank? ? 'No appreciation yet' : @notation.appreciation %>
</p>

<% if @questions.any? %>
    <%= render 'questions/table' %>
<% end %>

<div class="row">
  <h3>New question</h3>
  <%= render 'questions/form' %>
</div>

<div class="row">
    <%= link_to 'Edit', edit_notation_path(@notation) %> |
    <%= link_to 'Exam', @notation.exam %> |
    <%= link_to 'Back', :back %>
</div>