config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'users' => 'validation#index'
  get 'users/:user_id/validate' => 'validation#validate', as: :validate_user

  resources :questions

  resources :notations do
    resources :questions
  end

  resources :exams do
    resources :notations
    get 'validate' => 'exams#validate', as: :validate
   end

  root 'exams#index'

end

app/models/exam.rb
class Exam < ActiveRecord::Base

  has_many :notations
  has_many :questions, through: :notations
  belongs_to :user

  default_scope {
    order('created_at DESC')
  }

end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]
  before_action :user_validated, except: [:index]

  # GET /exams
  # GET /exams.json
  def index
    if current_user.valid
      @exams = Exam.all
    end
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
    @notations = @exam.notations
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)
    @exam.user = current_user

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def validate
    @exam = Exam.find(params[:exam_id])

    # User is the king
    if @exam.user_id == current_user.id || current_user.role == 'admin'
      @exam.notations.each do |notation|
        StudentMailer.exam_validation_email(notation).deliver
      end

      respond_to do |format|
        format.html { redirect_to @exam, notice: 'Exam was successfully validated.' }
        format.json { head :no_content }
      end
    # User is not the king, au goulag
    else
      respond_to do |format|
        format.html { redirect_to @exam, :alert => "Only the exam owner can close it" }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:course, :exam_type, :nb_questions, :average, :max, :min)
    end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_form.html.erb
<%= form_for @exam, :html => { :class => 'form-inline' } do |f| %>
  <% if @exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% @exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <%= f.label :course %><br>
    <%= f.text_field :course, :class => 'form-control' %>
  </div>
  <div class="row">
    <%= f.label :exam_type %><br>
    <%= f.text_field :exam_type, :class => 'form-control' %>
  </div>
  <div class="row">
    <%= f.label :nb_questions %><br>
    <%= f.number_field :nb_questions, :class => 'form-control small-field' %>
  </div>

  <div class="actions">
    <%= f.submit 'Save', :class => 'btn btn-primary' %>
  </div>

<% end %>

app/views/exams/edit.html.erb
<h1>Editing exam</h1>

<%= render 'form' %>

<div class="row">
  <%= link_to 'Show', @exam %> |
  <%= link_to 'Back', exams_path %>
</div>

app/views/exams/index.html.erb
<h1>STA On Air</h1>

<% if @exams && @exams.any? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Course</th>
          <th>Type</th>
          <th>Nb questions</th>
          <th>Average</th>
          <th>Max</th>
          <th>Min</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @exams.each do |exam| %>
          <tr>
            <td><%= exam.course %></td>
            <td><%= exam.exam_type %></td>
            <td><%= exam.nb_questions %></td>
            <td><span class="label label-info"><%= exam.average.blank? ? 'No mark' : exam.average %></span></td>
            <td><span class="label label-success"><%= exam.max.blank? ? 'No mark' : exam.max %></span></td>
            <td><span class="label label-danger"><%= exam.min.blank? ? 'No mark' : exam.min %></span></td>
            <td><%= link_to 'Show', exam %></td>
            <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
            <td><%= link_to 'Delete', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
<% end %>

<br>

<%= link_to 'New Exam', new_exam_path, :class => 'btn btn-primary' %>

app/views/exams/new.html.erb
<h1>New exam</h1>

<%= render 'form' %>

<div class="row">
  <%= link_to 'Back', exams_path %>
</div>

app/views/exams/show.html.erb
<p>
  <h2><%= @exam.course %> - <%= @exam.exam_type %></h2>
</p>

<p>
  <strong>Average  </strong>
  <span class="label label-info"><%= @exam.average.blank? ? 'No mark' : @exam.average %></span>

  <strong>Max  </strong>
  <span class="label label-success"><%= @exam.max.blank? ? 'No mark' : @exam.max %></span>

  <strong>Min  </strong>
  <span class="label label-danger"><%= @exam.min.blank? ? 'No mark' : @exam.min %></span>
</p>
<div class="row">
    <%= link_to 'New notation',  new_exam_notation_path(@exam), :class => 'btn btn-primary' %>
    <%= link_to 'Close exam',  exam_validate_path(@exam), { :class => 'btn btn-success', :id => 'validate-button', data: { confirm: 'Are you sure?' } } %>
</div>
<% if @notations.any? %>
    <%= render 'notations/table' %>
<% end %>

<div class="row">
  <%= link_to 'Edit', edit_exam_path(@exam) %> |
  <%= link_to 'Back', exams_path %>
</div>