config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'users' => 'validation#index'
  get 'users/:user_id/validate' => 'validation#validate', as: :validate_user

  resources :questions

  resources :notations do
    resources :questions
  end

  resources :exams do
    resources :notations
    get 'validate' => 'exams#validate', as: :validate
   end

  root 'exams#index'

end

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="">
        STA On Air
      </a>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to 'Exams list', root_path %></li>
      <li><%= link_to 'Notations list', notations_path %></li>
      <li><% if current_user && current_user.role == 'admin' %><%= link_to 'Users list', users_path %><% end %></li>
    </ul>
    <div class="navbar-text pull-right">
      <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StaOnAir</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'layouts/menu' %>
  </header>

  <div class="container">
    <div id="alerts">
      <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    </div>

    <%= yield %>
  </div>

</body>
</html>